config/routes.rb
Rails.application.routes.draw do
  root "english/latest_news#index"

	namespace :english do
		get "latest_news" => "latest_news#index"
		get "latest_news/in_latest" => "latest_news#in_latest"
		get "latest_news/zee_latest" => "latest_news#zee_latest"
		get "latest_news/ndtv_latest" => "latest_news#ndtv_latest"
		get "latest_news/toi_latest" => "latest_news#toi_latest"
		get "latest_news/oneindia_latest" => "latest_news#oneindia_latest"

		get "finance" => "finance#index"
		get "finance/money_control" => "finance#money_control"
		get "finance/et" => "finance#et"
		get "finance/zee" => "finance#zee"
		get "finance/market_action" => "finance#market_action"

		get "cricket" => "cricket#index"
		get "cricket/cb" => "cricket#cb"
		get "cricket/espn" => "cricket#espn"
	end
	namespace :hindi do
		get "latest_news" => "latest_news#index"
		get "latest_news/dainik" => "latest_news#dainik"
		get "latest_news/ndtv" => "latest_news#ndtv"
		get "latest_news/zee" => "latest_news#zee"
		get "latest_news/abp" => "latest_news#abp"
	end
	

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hindi_news.rb
class HindiNews < ApplicationRecord
	serialize :news
end

app/models/news.rb
class News < ApplicationRecord
	serialize :news
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	before_action :load_service, :load_sensex


private
	def load_service
	end

	def load_sensex
		@sensex = BaseService.new.fetch_sensex
		@style_class = (@sensex[2].starts_with?("-")) ? "text-danger" : "text-success"
	end
end

app/controllers/english/cricket_controller.rb
class English::CricketController < ApplicationController
  def index
  end

	def cb 
		@news = News.find_by(channel: "CB", news_type: "CRICKET")["news"]
    @base = "http://www.cricbuzz.com"
	end

	def espn
		@news = News.find_by(channel: "ESPN", news_type: "CRICKET")["news"]
		@base = "http://www.espncricinfo.com"
	end

private
	def load_service
		@service = CricketService.new
	end
	
end

app/controllers/english/finance_controller.rb
class English::FinanceController < ApplicationController
  def index
		@market = @service.fetch_today_stock_action
  end

	def market_action
		@result = @service.fetch_today_stock_action
		render json: @result
  end

	def money_control
		@news = News.find_by(channel: "MoneyControl", news_type: "FINANCE")["news"]
    @base = "http://www.moneycontrol.com"
	end

	def et
		@news = News.find_by(channel: "ET", news_type: "FINANCE")["news"]
		@base = "http://economictimes.indiatimes.com"
	end

	def zee
		@news = News.find_by(channel: "ZEE", news_type: "FINANCE")["news"]
		@base = "http://zeenews.india.com"
	end
	

private
	def load_service
		@service = FinanceService.new
	end
	
end

app/controllers/english/latest_news_controller.rb
class English::LatestNewsController < ApplicationController
  def index
  end

	def in_latest
		@news = News.find_by(channel: "INTODAY", news_type: "LATEST")["news"]
    @base = "http://indiatoday.intoday.in/"
  end

  def zee_latest
		@news = News.find_by(channel: "ZEE", news_type: "LATEST")["news"]
    @base = "http://zeenews.india.com"
	end

	def ndtv_latest
		@news = News.find_by(channel: "NDTV", news_type: "LATEST")["news"]
  end

  def toi_latest
		@news = News.find_by(channel: "TOI", news_type: "LATEST")["news"]
    @base = "http://timesofindia.indiatimes.com"
    @img_base = "http://timesofindia.indiatimes.com"
  end
	
	def oneindia_latest
		@news = News.find_by(channel: "ONEINDIA", news_type: "LATEST")["news"]
	end

private
	def load_service
		@service = MainService.new
		@base = ""
    @img_base = ""
	end
	
end

app/controllers/finance_controller.rb
class FinanceController < ApplicationController
  def index
  end

	def market_action
		@result = @service.fetch_today_stock_action
		render json: @result
  end

private
	def load_service
		@service = FinanceService.new
	end
	
end

app/controllers/hindi/latest_news_controller.rb
class Hindi::LatestNewsController < ApplicationController
  def index
  end

	def dainik
		@news = HindiNews.find_by(channel: "DAINIK", news_type: "LATEST")["news"]
    @base = "http://www.jagran.com"
  end

	def ndtv
		@news = HindiNews.find_by(channel: "NDTV", news_type: "LATEST")["news"]
	end

	def zee
		@news = HindiNews.find_by(channel: "ZEE", news_type: "LATEST")["news"]
	end

	def abp 
		@news = HindiNews.find_by(channel: "ABP", news_type: "LATEST")["news"]
	end

private
	def load_service
		@service = HindiNewsService.new
		@base = ""
    @img_base = ""
	end
	
end

app/controllers/hindi_news_controller.rb
class HindiNewsController < ApplicationController
  def index
  end

	def dainik
		@news = HindiNews.find_by(channel: "DAINIK", news_type: "LATEST")["news"]
    @base = "http://www.jagran.com"
  end

	def ndtv
		@news = HindiNews.find_by(channel: "NDTV", news_type: "LATEST")["news"]
	end

	def zee
		@news = HindiNews.find_by(channel: "ZEE", news_type: "LATEST")["news"]
	end

	def abp 
		@news = HindiNews.find_by(channel: "ABP", news_type: "LATEST")["news"]
	end

private
	def load_service
		@service = HindiNewsService.new
		@base = ""
    @img_base = ""
	end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

	def in_latest
		@news = News.find_by(channel: "INTODAY", news_type: "LATEST")["news"]
    @base = "http://indiatoday.intoday.in/"
  end

  def zee_latest
		@news = News.find_by(channel: "ZEE", news_type: "LATEST")["news"]
    @base = "http://zeenews.india.com"
	end

	def ndtv_latest
		@news = News.find_by(channel: "NDTV", news_type: "LATEST")["news"]
  end

  def toi_latest
		@news = News.find_by(channel: "TOI", news_type: "LATEST")["news"]
    @base = "http://timesofindia.indiatimes.com"
    @img_base = "http://timesofindia.indiatimes.com"
  end
	
	def oneindia_latest
		@news = News.find_by(channel: "ONEINDIA", news_type: "LATEST")["news"]
	end

private
	def load_service
		@service = MainService.new
		@base = ""
    @img_base = ""
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_infominer_news.html.erb
<!--
<table class="table">
      <tbody>
    <%# @news.each do |n| %>
      <%# next if n["Title"].nil? or n["Title"].empty? %>
        <tr>
          <td style="width:90%"><h3><a href="<%#= @base %><%#= n['Link'] %>" target="_blank"><%#= n["Title"] %></a></h3></td>
          <td style="width:10%"><img src="<%#= @img_base %><%#= n['ImgLink']%>" width="140" height="90" /></td>
        </tr>
    <%# end %>
      </tbody>
</table>
-->
	<% @news.each_slice(3) do |row_items| %>
	<div style="margin-top:20px;"></div>
		<div class="row">
		<% row_items.each do |n| %>
      <% next if n["Title"].nil? or n["Title"].empty? %>
			<div class="col-lg-4">
				<div jsname="WsjYwc" class="Ihwked UB0dDd GcESAf XkfHGe  hE2QI iFJd6c" data-iid="z13rc5iyor3jethf323lhzxrzszaf1qqh04" jsaction="click:qkHMFc" jslog="6941; 1:z13rc5iyor3jethf323lhzxrzszaf1qqh04; track:impression,click" tabindex="-1" aria-label="Post view" role="region" style="">
            <div class="ELUvyf">
              <div jsname="uwfEUd" id="body:i46">
                <div class="fu5e3b sMVRZe" style="">
                  <div class="wftCae" jsname="EjRJtf" dir="ltr"><h3><a href="<%= @base %><%= n['Link'] %>" target="_blank"><%= n["Title"] %></a></h3> </div>
                </div>
              </div>
            </div>
            <div jsname="MTOxpb">
              <div>
                <div class="UE4aic" id="i47" jscontroller="hzMnDc" jsmodel="bTCmc" jsdata="LfLzDd;https://plus.google.com/photos/106059307368713535123/albums/6376103554456787041?authkey=CJPk1aW4-5zOLQ;42" jsaction="click:KjsqPd(preventDefault=true);H5bEoe:KjsqPd(preventDefault=true);">
                  <div class="tOS5" jscontroller="MaIFyc" jsmodel="bTCmc" jsdata="LfLzDd;https://plus.google.com/photos/106059307368713535123/albums/6376103554456787041?authkey=CJPk1aW4-5zOLQ;42" jsaction="rcuQ6b:npT2md;JoGwKe:CfS0pe;xRhIYd:Yr1Sef; touchstart:QOfrR;">
                    <div class="WvxPQb" jsname="A08Sxc">
									<% if !n['ImgLink'].nil? and !n['ImgLink'].empty? %>
                      <img class="qRwspd qnIxAe news_image" jsname="xJzy8c"  data-width="2048" data-height="1536" src="<%= @img_base %><%= n['ImgLink']%>" onerror="this.src='/assets/logo-cb9812f855b22901e8ba508c1d70bc62984c5abcda27a61dd156fbbebf6ddc3e.png'"alt="Photo" width="400" height="200">
									<% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
			</div>
		<% end %>
		</div>
	<% end %>

app/views/english/cricket/cb.js.erb
$("#cb").html("<%= escape_javascript(render partial: 'infominer_news')%>")

app/views/english/cricket/espn.js.erb
$("#espn").html("<%= escape_javascript(render partial: 'infominer_news')%>")

app/views/english/cricket/index.html.erb
<ul class="nav nav-tabs">
  <li class="active"><a href="#cb" data-toggle="tab">CricBuzz</a></li>
  <li><a href="#espn" data-toggle="tab">ESPN</a></li>
</ul>
<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade active in" id="cb"><center><%= image_tag "spinner.gif" %></center></div>
  <div class="tab-pane fade" id="espn"><center><%= image_tag "spinner.gif" %></center></div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $.get("<%= english_cricket_cb_path %>");
    $.get("<%= english_cricket_espn_path %>");
  });
</script>

app/views/english/finance/_most_active.html.erb
<div class="col-sm-4"> 
		<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">Most Active (NSE)</h3>
				</div>
				<div class="panel-body">
					<table class="table table-striped table-hover ">
						<thead>
							<tr> <th>Company</th> <th>Current</th> <th>Value</th> </tr>
						</thead>
						<tbody>
						<% @market["MostActiveStock"].each do |gainer| %>
							<tr>
								<td><%= gainer["Company"] %></td>
								<td><%= gainer["Current"] %></td>
								<td><%= gainer["Value"] %></td>
							</tr>
						<% end %>
						</tbody>
					</table>
				</div>
			</div>
	</div>

app/views/english/finance/_top_gainer.html.erb
<div class="col-sm-6"> 
		<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">Top Gainer (NSE)</h3>
				</div>
				<div class="panel-body">
					<table class="table table-striped table-hover ">
						<thead>
							<tr> <th>Company</th> <th>Current</th> <th>Gain</th> </tr>
						</thead>
						<tbody>
						<% @market["TopGainer"].each do |gainer| %>
							<tr>
								<td><%= gainer["Company"] %></td>
								<td><%= gainer["CurrentPrice"] %></td>
								<td><%= gainer["GainPercentage"] %> %</td>
							</tr>
						<% end %>
						</tbody>
					</table>
				</div>
			</div>
	</div>

app/views/english/finance/_top_looser.html.erb
<div class="col-sm-6"> 
		<div class="panel panel-danger">
				<div class="panel-heading">
					<h3 class="panel-title">Top Looser (NSE)</h3>
				</div>
				<div class="panel-body">
					<table class="table table-striped table-hover ">
						<thead>
							<tr> <th>Company</th> <th>Current</th> <th>Loss</th> </tr>
						</thead>
						<tbody>
						<% @market["TopLooser"].each do |gainer| %>
							<tr>
								<td><%= gainer["Company"] %></td>
								<td><%= gainer["CurrentPrice"] %></td>
								<td><%= gainer["LossPercentage"] %> %</td>
							</tr>
						<% end %>
						</tbody>
					</table>
				</div>
			</div>
	</div>

app/views/english/finance/et.js.erb
$("#et").html("<%= escape_javascript(render partial: 'infominer_news')%>")

app/views/english/finance/index.html.erb
<div class="row">
		<%= render "top_gainer" %>
		<%= render "top_looser" %>
</div>

<ul class="nav nav-tabs">
  <li class="active"><a href="#mc" data-toggle="tab">MoneyControl</a></li>
  <li><a href="#et" data-toggle="tab">ET</a></li>
  <li><a href="#zee" data-toggle="tab">Zee</a></li>
</ul>
<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade active in" id="mc"><center><%= image_tag "spinner.gif" %></center></div>
  <div class="tab-pane fade" id="et"><center><%= image_tag "spinner.gif" %></center></div>
  <div class="tab-pane fade" id="zee"><center><%= image_tag "spinner.gif" %></center></div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $.get("<%= english_finance_money_control_path %>");
    $.get("<%= english_finance_et_path %>");
    $.get("<%= english_finance_zee_path %>");
  });
</script>

app/views/english/finance/money_control.js.erb
$("#mc").html("<%= escape_javascript(render partial: 'infominer_news')%>")

app/views/english/finance/zee.js.erb
$("#zee").html("<%= escape_javascript(render partial: 'infominer_news')%>")

app/views/english/latest_news/in_latest.js.erb
$("#intoday").html("<%= escape_javascript(render partial: 'infominer_news')%>")

app/views/english/latest_news/index.html.erb
<ul class="nav nav-tabs">
  <li class="active"><a href="#toi" data-toggle="tab">Toi</a></li>
  <li><a href="#zee" data-toggle="tab">Zee</a></li>
  <li><a href="#ndtv" data-toggle="tab">Ndtv</a></li>
  <li><a href="#intoday" data-toggle="tab">InToday</a></li>
  <li><a href="#oneindia" data-toggle="tab">OneIndia</a></li>
</ul>
<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade active in" id="toi"><center><%= image_tag "spinner.gif" %></center></div>
  <div class="tab-pane fade" id="zee"><center><%= image_tag "spinner.gif" %></center></div>
  <div class="tab-pane fade" id="ndtv"><center><%= image_tag "spinner.gif" %></center></div>
  <div class="tab-pane fade" id="intoday"><center><%= image_tag "spinner.gif" %></center></div>
  <div class="tab-pane fade" id="oneindia"><center><%= image_tag "spinner.gif" %></center></div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $.get("<%= english_latest_news_toi_latest_path %>");
    $.get("<%= english_latest_news_zee_latest_path %>");
    $.get("<%= english_latest_news_ndtv_latest_path %>");
    $.get("<%= english_latest_news_in_latest_path %>");
    $.get("<%= english_latest_news_oneindia_latest_path %>");
  });
</script>

app/views/english/latest_news/ndtv_latest.js.erb
$("#ndtv").html("<%= escape_javascript(render partial: 'infominer_news')%>")

app/views/english/latest_news/oneindia_latest.js.erb
$("#oneindia").html("<%= escape_javascript(render partial: 'infominer_news')%>")

app/views/english/latest_news/toi_latest.js.erb
$("#toi").html("<%= escape_javascript(render partial: 'infominer_news')%>")

app/views/english/latest_news/zee_latest.js.erb
$("#zee").html("<%= escape_javascript(render partial: 'infominer_news')%>")

app/views/hindi/latest_news/_infominer_news_old.html.erb
<table class="table">
      <tbody>
    <% @news.each do |n| %>
      <% next if n["Title"].nil? or n["Title"].empty? %>
        <tr>
          <td style="width:90%"><h3><a href="<%= @base %><%= n['Link'] %>" target="_blank"><%= n["Title"] %></a></h3></td>
          <td style="width:10%"><img src="<%= @img_base %><%= n['ImgLink']%>" width="140" height="90" /></td>
        </tr>
    <% end %>
      </tbody>
</table>

app/views/hindi/latest_news/abp.js.erb
$("#abp").html("<%= escape_javascript(render partial: 'infominer_news')%>")

app/views/hindi/latest_news/dainik.js.erb
$("#dainik").html("<%= escape_javascript(render partial: 'infominer_news')%>")

app/views/hindi/latest_news/index.html.erb
<ul class="nav nav-tabs">
  <li class="active"><a href="#abp" data-toggle="tab">Abp</a></li>
  <li><a href="#zee" data-toggle="tab">Zee</a></li>
  <li><a href="#dainik" data-toggle="tab">Dainik</a></li>
  <li><a href="#ndtv" data-toggle="tab">Ndtv</a></li>
</ul>
<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade active in " id="abp"><center><%= image_tag "spinner.gif" %></center></div>
  <div class="tab-pane fade" id="zee"><center><%= image_tag "spinner.gif" %></center></div>
  <div class="tab-pane fade" id="dainik"><center><%= image_tag "spinner.gif" %></center></div>
  <div class="tab-pane fade" id="ndtv"><center><%= image_tag "spinner.gif" %></center></div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $.get("<%= hindi_latest_news_abp_path %>");
    $.get("<%= hindi_latest_news_zee_path %>");
    $.get("<%= hindi_latest_news_dainik_path %>");
    $.get("<%= hindi_latest_news_ndtv_path %>");
  })
</script>

app/views/hindi/latest_news/ndtv.js.erb
$("#ndtv").html("<%= escape_javascript(render partial: 'infominer_news')%>")

app/views/hindi_news/index.html.erb
<ul class="nav nav-tabs">
  <li class="active"><a href="#abp" data-toggle="tab">Abp</a></li>
  <li><a href="#zee" data-toggle="tab">Zee</a></li>
  <li><a href="#dainik" data-toggle="tab">Dainik</a></li>
  <li><a href="#ndtv" data-toggle="tab">Ndtv</a></li>
</ul>
<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade active in " id="abp"><center><%= image_tag "spinner.gif" %></center></div>
  <div class="tab-pane fade" id="zee"><center><%= image_tag "spinner.gif" %></center></div>
  <div class="tab-pane fade" id="dainik"><center><%= image_tag "spinner.gif" %></center></div>
  <div class="tab-pane fade" id="ndtv"><center><%= image_tag "spinner.gif" %></center></div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $.get("/hindi_news/abp");
    $.get("/hindi_news/zee");
    $.get("/hindi_news/dainik");
    $.get("/hindi_news/ndtv");
  })
</script>

app/views/home/index.html.erb
<ul class="nav nav-tabs">
  <li class="active"><a href="#toi" data-toggle="tab">Toi</a></li>
  <li><a href="#zee" data-toggle="tab">Zee</a></li>
  <li><a href="#ndtv" data-toggle="tab">Ndtv</a></li>
  <li><a href="#intoday" data-toggle="tab">InToday</a></li>
  <li><a href="#oneindia" data-toggle="tab">OneIndia</a></li>
</ul>
<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade active in" id="toi"><center><%= image_tag "spinner.gif" %></center></div>
  <div class="tab-pane fade" id="zee"><center><%= image_tag "spinner.gif" %></center></div>
  <div class="tab-pane fade" id="ndtv"><center><%= image_tag "spinner.gif" %></center></div>
  <div class="tab-pane fade" id="intoday"><center><%= image_tag "spinner.gif" %></center></div>
  <div class="tab-pane fade" id="oneindia"><center><%= image_tag "spinner.gif" %></center></div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $.get("/home/toi_latest");
    $.get("/home/zee_latest");
    $.get("/home/ndtv_latest");
    $.get("/home/in_latest");
    $.get("/home/oneindia_latest");
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Latest Khabar</title>
    <%= csrf_meta_tags %>
		<meta name="description" content="Hindi English News From Different Sources">
		<meta name="keywords" content="Hindi News, English News, Latest News, News From Different Sources, Ndtv, aaj tak, zee news, one india, times of india, dainik jagran">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
		<script>
					(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
					(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
					m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
					})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

					ga('create', 'UA-59952073-5', 'auto');
					ga('send', 'pageview');
				</script>


		<%= render "layouts/partials/navbar" %> 
    <div> 
      <div class="page-header" id="banner">   </div> 
			<div class="container"> 	 
				<div class="spacer"></div>
				<%= render "layouts/partials/sensex" %> 
    		<%= yield %>

			<!-- Google Ads -->
				<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- vishal1 -->
        <div class="row">
          <ins class="adsbygoogle"
            style="display:block"
            data-ad-client="ca-pub-8007076293299638"
            data-ad-slot="1350956302"
            data-ad-format="auto"></ins>
        </div>
        <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
        </script>

			<!-- AdNow -->
<!--
				<div class="row"><div id="SC_TBlock_241513" class="SC_TBlock">loading...</div></div> 
<script type="text/javascript">var SC_CId = "241513",SC_Domain="n.ads1-adnow.com";SC_Start_241513=(new Date).getTime();</script>
<script type="text/javascript" src="//st-n.ads1-adnow.com/js/adv_out.js"></script>
-->
		<%= render "layouts/partials/footer" %> 
			</div>
		</div>
  </body>
</html>

app/views/layouts/partials/_footer.html.erb
<footer>
				<div style="margin-top:40px;"></div>
        <div class="row navbar-default">
          <div class="col-lg-12">
            <p> Contact me at <a href="mailto:vishalpundir49@gmail.com">vishalpundir49@gmail.com</a>.</p>
          </div>
        </div>

</footer>

app/views/layouts/partials/_navbar.html.erb
		<div class="navbar navbar-default navbar-fixed-top"> 
      <div class="container"> 
        <div class="navbar-header"> 
          <a class="navbar-brand" href=""><%=image_tag "logo.png", width: 130, height: 50 %></a><br/> 
          
          <button data-target="#navbar-main" data-toggle="collapse" type="button" class="navbar-toggle"> 
            <span class="icon-bar"></span> 
            <span class="icon-bar"></span> 
            <span class="icon-bar"></span> 
          </button> 
        </div> 
        <div id="navbar-main" class="navbar-collapse collapse" ng-controller="SearchCtrl"> 
          <div class="nav navbar-nav navbar-right"> 
            <ul class="nav navbar-nav"> 
              <li class="dropdown"><%= link_to root_path, {class: "dropdown-toggle", "data-toggle": "dropdown","role": "button", "aria-expanded": "false"} do %> 
										English <span class="caret"></span>
									<% end %>
          			<ul class="dropdown-menu" role="menu">
									<li> <%= link_to "Latest", root_path %></li>
									<li> <%= link_to "Finance", english_finance_path %></li>
									<li> <%= link_to "Cricket", english_cricket_path %></li>
								</ul>
							</li> 
              <li><%= link_to "Hindi", hindi_latest_news_path %> </li> 
            </ul>  
          </div> 
        </div> 
 
      </div> 
    </div>

app/views/layouts/partials/_sensex.html.erb
<div class="row">
  <span style="float:right" class="<%= @style_class %>"><span style="font-size:24px"><i>sensex:</i></span> <%= @sensex[1]%> (<%= @sensex[2]%>, <%= @sensex[3] %>%)</span>
</div>